site_name: Zen UV for Blender
site_description: Zen UV for Blender Documentation
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Operators: operators.md
    - Pie Menu: pie-menu.md
    - Controls: controls.md
    - Preferences: preferences.md
    - Troubleshooting: troubleshooting.md
    # - Changelog: changelog.md
docs_dir: mkdocs
site_dir: docs
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition