site_name: Zen UV for Blender
site_description: Zen UV for Blender Documentation
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Pie Menu: pie-menu.md
    - UV Maps: adv_uv-maps.md
    # - Operators: operators.md
    - Unwrap: unwrap.md
    - Select: select.md
    - Pack: pack.md
    - Checker Map: checker.md
    # - Controls: controls.md
    - Preferences: preferences.md
    - Help: help.md
    - Troubleshooting: troubleshooting.md
    - Changelog: changelog.md
docs_dir: mkdocs
site_dir: docs
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition